---
title: "GAMBLR family of packages"
---

GAMBLR.viz is the top-most member of the [GAMBLR]((https://github.com/morinlab/GAMBLR))
family of packages that is designed to be used outside of GSC and for users who
are not members of Morin Lab.
It mostly serves the purpose of providing functions for high-level visualizations
of genomic data, including simple somatic mutations, structural variations, copy
number alterations, and combinations of these data.


The GAMBLR family includes:

* [GAMBLR.data](https://github.com/morinlab/GAMBLR.viz) - collection of genomic
data for analysis of Mature B-cell neoplasms
* [GAMBLR.helpers](https://github.com/morinlab/GAMBLR.helpers) - a set of
low-level functions for data operation
* [GAMBLR.utils](https://github.com/morinlab/GAMBLR.utils) - higher level set of
functions to operate on genomic data
* GAMBLR.viz - this package
* [GAMBLR.results](https://github.com/morinlab/GAMBLR.results) - used to access
the full data in GAMBL project. Only available for members of the Morin Lab and
requires access to GSC, but can also be run locally once properly configured and
synced.

This diagram illustrates in a simplified way the dependency relationship of
different packages in the GAMBLR.family:

```{mermaid}
flowchart LR
  A("GAMBLR.data") --> B("GAMBLR.helpers")
  B --> C("GAMBLR.utils")
  C --> D("GAMBLR.viz")
  D --> E{"Morin Lab member?"}
  E -- YES --> F("GAMBLR.results")
  E -- NO --> A
```

All dependencies should be installed automatically for you, just like with any
other R package.
If not, please report the issue in the appropriate GitHub repo.
