#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom GAMBLR annotate_sv
#' @importFrom GAMBLR assign_cn_to_ssm
#' @importFrom GAMBLR calc_mutation_frequency_bin_regions
#' @importFrom GAMBLR cnvKompare
#' @importFrom GAMBLR collate_results
#' @importFrom GAMBLR fread_maf
#' @importFrom GAMBLR gene_to_region
#' @importFrom GAMBLR get_cn_segments
#' @importFrom GAMBLR get_combined_sv
#' @importFrom GAMBLR get_manta_sv
#' @importFrom GAMBLR get_sample_cn_segments
#' @importFrom GAMBLR get_ssm_by_region
#' @importFrom GAMBLR get_ssm_by_sample
#' @importFrom GAMBLR.helpers check_config_value
#' @importFrom GAMBLR.helpers coding_vc
#' @importFrom GAMBLR.helpers process_regions
#' @importFrom GAMBLR.helpers rainfall_conv
#' @importFrom GAMBLR.helpers region_to_chunks
#' @importFrom GAMBLR.helpers standardize_chr_prefix
#' @importFrom GAMBLR.helpers subset_cnstates
#' @importFrom graphics legend
#' @importFrom graphics text
#' @importFrom grDevices col2rgb
#' @importFrom grDevices dev.off
#' @importFrom grDevices pdf
#' @importFrom grDevices png
#' @importFrom grDevices rainbow
#' @importFrom grDevices rgb
#' @importFrom grid gpar
#' @importFrom grid grid.grabExpr
#' @importFrom grid grid.rect
#' @importFrom grid textGrob
#' @importFrom methods formalArgs
#' @importFrom stats aggregate
#' @importFrom stats end
#' @importFrom stats fisher.test
#' @importFrom stats frequency
#' @importFrom stats p.adjust
#' @importFrom stats setNames
#' @importFrom stats start
#' @importFrom utils data
#' @importFrom utils head
#' @importFrom utils read.table
#' @importFrom utils write.table
## usethis namespace: end
NULL
